### ISSUE TITLE
Merging all linters into one.

### ISSUE THREAD

**Issue by sunshinejr** [ashfurrow/danger-swiftlint#11]
Hey Ash!

So I've been finishing my [danger-xiblint plugin](https://github.com/sunshinejr/danger-xiblint) and I found myself copying most of your infrastructure. Then I thought that maybe we could create a general plugin for linters, because they share a big amount of code.

**Pros:**
- all in one - I could use all linters I want without searching and installing for another library
- API consistency across linters
- when new version of Danger/Swift comes, only one package would need to be updated
- easier for adding additional linters for Danger Swift infra

**Cons:**
- not sure if it's scalable
- we would need some people to help if there'll be more interest for this one
- architecting the general plugin to make it easy to both maintain & add new linters

I'd be eager to hear your opinion, because I'm still debating if it's the right choice myself! 😅

**Comment by ashfurrow** [comment]
Hmm interesting. My initial reaction is that the cons would likely outweigh the pros, but there's not an immediate answer. I could imagine a separate Swift package just for helpers and common logic that could be shared amongst the different linter Danger plugins. It's a tough call. But I'm also a lot less concerned with repeated code than I used to be. /cc @orta.

**Comment by orta** [comment]
It's hard to grok how the world splits up code in the SPM world from my vantage point. From the perspective of these two libs, my main worry would be making sure they are both ok with using the same version of the central lib, but Server should handle that.

TBH, another option is to say "this shared code should go in Danger because it's useful to every plugin" and that might get some easy returns on simplifying both of these libs

**Comment by sunshinejr** [comment]
Ok cool, I'm gonna close it for now as I don't see a point for it _right now_, maybe when I got some more thoughts I will reopen in the future. Thanks guys!
